# Generated by Django 5.2.1 on 2025-05-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='algorithm',
            field=models.CharField(choices=[('algorithm1', '算法1'), ('algorithm2', '算法2'), ('algorithm3', '算法3'), ('algorithm4', '算法4 - 哈希计算')], max_length=100),
        ),
    ]
