# Generated by Django 5.2.1 on 2025-05-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='algorithm',
            field=models.CharField(choices=[('algorithm1', '灰度处理'), ('algorithm2', '边缘检测'), ('algorithm3', '物体识别'), ('algorithm4', '哈希计算')], max_length=100),
        ),
    ]
