# Generated by Django 5.2.1 on 2025-05-17 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_image_hash'),
        ('tasks', '0003_task_progress_alter_task_algorithm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': '任务', 'verbose_name_plural': '任务列表'},
        ),
        migrations.AddField(
            model_name='task',
            name='celery_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery任务ID'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='任务描述'),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='algorithm',
            field=models.CharField(choices=[('algorithm1', '灰度处理'), ('algorithm2', '边缘检测'), ('algorithm3', '风格迁移'), ('algorithm4', '色彩增强')], max_length=50, verbose_name='算法'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='task',
            name='failure_reason',
            field=models.TextField(blank=True, null=True, verbose_name='失败原因'),
        ),
        migrations.AlterField(
            model_name='task',
            name='images',
            field=models.ManyToManyField(related_name='tasks', to='images.image', verbose_name='图像'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.FloatField(default=0.0, verbose_name='进度'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', '等待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
