# Generated by Django 5.2.1 on 2025-05-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='algorithms',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
