# Generated by Django 5.2.1 on 2025-05-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_image_hash'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE images_image DROP COLUMN path;",
            reverse_sql=(
                "ALTER TABLE images_image ADD COLUMN "
                "path varchar(500) NOT NULL DEFAULT '';"
            ),
        ),
    ]
